### ISSUE TITLE
Request: an add time function for some timer parameters

### ISSUE THREAD

**Issue by ErSulba** [aluisiora/routeros-client#7]
This is something i was trying to handle with some regex extracting the values that the API returns and add the time i want for example:

let's say that i have a user in the hotspot which returns the value 

`limitUptime='1d12h'`

but if i want to increase that limit with something like `limitUptime + "1h"` isn't possible without lots of manually regex, split and join methods for that string, so a helper function for this would be a realive.

**Comment by aluisiora** [comment]
I'm sorry but this shouldn't be something that should be handled by the routeros client api but some other lib with this exact purpose. You can try using something like [momentjs](https://momentjs.com/) which has a very powerfull date and time manipulation.

I'm closing it now since this feature is not on the scope of the lib.
